In [2]:
from cminpack_numba import lmdif1, lmdif, lmdif_sig
import numpy as np
import numba as nb
from scipy.optimize import leastsq


@nb.cfunc(lmdif_sig)
def func_numba(udata, m, n, x, fvec, iflag):
    fvec[0] = 2.0 * (x[0] - 3.0) ** 2 + 1.0*x[1]
    fvec[1] = 3.0 * (x[0] - 4.0) ** 2 + 2.0*x[1]
    fvec[2] = 4.0 * (x[0] - 5.0) ** 2 + 3.0*x[1]
    fvec[3] = 5.0 * (x[0] - 6.0) ** 2 + 4.0*x[1]
    fvec[4] = 6.0 * (x[0] - 7.0) ** 2 + 5.0*x[1]
    return 0

def func_scipy(x, args=()):
    return np.array([2.0 * (x[0] - 3.0) ** 2 + 1.0*x[1], 3.0 * (x[0] - 4.0) ** 2 + 2.0*x[1], 4.0 * (x[0] - 5.0) ** 2 + 3.0*x[1], 5.0 * (x[0] - 6.0) ** 2 + 4.0*x[1], 6.0 * (x[0] - 7.0) ** 2 + 5.0*x[1]])


In [3]:
leastsq(func_scipy, [0.0, 0.0], full_output=True)

(array([ 5.34948832, -2.06584694]),
 array([[0.00224468, 0.00371682],
        [0.00371682, 0.02433627]]),
 {'fvec': array([ 8.9743438 ,  1.33166231, -5.70897246, -6.14756052,  6.01589815]),
  'nfev': 26,
  'fjac': array([[-24.41919434,   0.33158155,   0.1144976 ,  -0.26639192,
           -0.81108702],
         [  3.72948693,  -6.41022054,   0.50320715,   0.54209607,
            0.53061976]]),
  'ipvt': array([1, 2], dtype=int32),
  'qtf': array([-7.33239827e-05, -4.30875351e-05])},
 'Both actual and predicted relative reductions in the sum of squares\n  are at most 0.000000',
 1)

In [4]:
lmdif1(func_numba.address, 5, np.array([0.0, 0.0]))

(array([ 5.34948832, -2.06584691]),
 array([ 8.97434385,  1.33166238, -5.70897239, -6.14756044,  6.01589821]),
 1)

In [5]:
lmdif(func_numba.address, 5, np.array([0.0, 0.0]))

(array([ 5.34948832, -2.06584691]),
 array([ 8.97434385,  1.33166238, -5.70897239, -6.14756044,  6.01589821]),
 array([[-24.41919426,   0.33158155],
        [  0.1144976 ,  -0.26639192],
        [ -0.81108701,   3.72948691],
        [ -6.41022053,   0.50320716],
        [  0.54209607,   0.53061975]]),
 array([1, 2], dtype=int32),
 array([-7.33541237e-05, -4.29710722e-05]),
 26,
 1)